### PR TITLE
Change Devise strategy base class

### PR DESCRIPTION
**Pull request by tvdeyen**
`solidus_auth_devise` has the Rememberable module included.

This adds the possiblity for stores to add support for sending `remember_me` with params and
let the Devise strategies send the necessary cookie.

### CODE REVIEW

**Comment by skukx** [comment]
Hey @tvdeyen,

Thank you for the PR! I'm not sure how `remember me` fits into jwt implementations though. This is essentially what the refresh token is for. Could you provide some use case examples so that I can better understand?

**Comment by tvdeyen** [comment]
We store the tokens in cookies that get deleted on browser close (host only session cookies).

If the user ticks the "remember me" checkbox while logging in we set an expiration date (7 days in the future), so that the cookie survives browser sessions. Otherwise the user wouldn't be remembered, right?

In my - admittedly sparse - understanding one uses the JWT refresh token only if the short lived access token has expired (most likely because the user is logged in longer than 60 minutes).

How do you implement "remember me" with the the refresh token alone?

**Comment by skukx** [comment]
Typically this will be up to the client for how long they want to persist tokens.

This conversation I think highlights the issue pretty well:
https://github.com/tymondesigns/jwt-auth/issues/261

Basically, jwt is meant to be stateless authentication.

https://github.com/tymondesigns/jwt-auth/issues/261#issuecomment-148216917
> Your API doesn't store the session (at least it shouldn't), that is where the "remember" information would be stored. JWTAuth validates username and password only and then generates a token to send back.
> 
> If you want your client application to remember the user, you have to store the token in a permanent cookie or local storage for your client application to look for and then skip the login page if found.
> 
> I would also add in some method to validate the token before letting them into the site before they get an error that the token is invalid.

https://github.com/tymondesigns/jwt-auth/issues/261#issuecomment-152990085
> So , the thing is **JWT Auth doesn't come with any thing to handle Remember Me or Forgot Password** functionanlity , it's something that you will have to handle
> 
> ### 1) About Remember Me
> What you can do is use the JWTAuth and set time to expire to a really long time if the user selects Remember Me .. that way the token will not expire and you can reuse the token anytime , you don't have to ask the user to log in again.
> 
> ### 2)About Forgot Password
> JWTAuth has got nothing to do with forgot password , you will have write code by yourself to handle if the user cannot remember the password .
> Using the standard approach of emailing a randomly generated reset password link should do the trick !
>

**Comment by tvdeyen** [comment]
Thanks for the insights.

> Typically this will be up to the client for how long they want to persist tokens.

Yes. This is exactly what we are doing.

> This conversation I think highlights the issue pretty well:
> [tymondesigns/jwt-auth#261](https://github.com/tymondesigns/jwt-auth/issues/261)
> 
> Basically, jwt is meant to be stateless authentication.

Yes, absolutely.

> [tymondesigns/jwt-auth#261 (comment)](https://github.com/tymondesigns/jwt-auth/issues/261#issuecomment-148216917)
> 
> > Your API doesn't store the session (at least it shouldn't), that is where the "remember" information would be stored. JWTAuth validates username and password only and then generates a token to send back.
> > If you want your client application to remember the user, you have to store the token in a permanent cookie or local storage for your client application to look for and then skip the login page if found.

Exactly what we are doing. (btw. `LocalStorage` **is not secure** and [**should not be used to store sensitive information**](https://auth0.com/docs/tokens/guides/store-tokens#don-t-store-tokens-in-local-storage), since [cross origin scripts can access local storage](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md#local-storage), while Cookies do not allow this.)

> > I would also add in some method to validate the token before letting them into the site before they get an error that the token is invalid.
> 
> [tymondesigns/jwt-auth#261 (comment)](https://github.com/tymondesigns/jwt-auth/issues/261#issuecomment-152990085)
> 
> > So , the thing is **JWT Auth doesn't come with any thing to handle Remember Me or Forgot Password** functionanlity , it's something that you will have to handle
> > ### 1) About Remember Me
> > What you can do is use the JWTAuth and set time to expire to a really long time if the user selects Remember Me .. that way the token will not expire and you can reuse the token anytime , you don't have to ask the user to log in again.
> > ### 2)About Forgot Password
> > JWTAuth has got nothing to do with forgot password , you will have write code by yourself to handle if the user cannot remember the password .
> > Using the standard approach of emailing a randomly generated reset password link should do the trick !

Check. We handle the "remember me" functionality in our client app. 

The reason why I opened this PR is because we need to be able to support both (old Cookie based remember for non-API based requests and "new" API based requests) within the same app. 

But this is solely a problem in our app that we will deal with on our end. I will remove the commits that return the "old-way" cookie from this PR.

What we _still need_ from this gem, though, is _the possibility_ to return a cookie for legacy authentication. So, we **still need the changed base class**. Otherwise it would be very hard for us to implement the necessary code on our end and [it is **the recommend way of creating custom Devise strategies** anyway](https://github.com/heartcombo/devise/blob/master/lib/devise/strategies/authenticatable.rb#L7-L9)

Thanks again for the information, that gave me the confidence that we are doing the right things on our end.

Will you accept the change of base classes? That would be very helpful for us and does not change onything for other users.

**Comment by skukx** [comment]
Looks good to me. I'll do a beta release this week and if things work out I'll bump version and do a version release

**Pull request merged**
